app/models/user.py
from flask.ext.login import LoginManager, login_required
from app.database import db

from datetime import datetime
from flask.ext.bcrypt import Bcrypt

crypt = Bcrypt()

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(250))
    email = db.Column(db.String(120), unique=True)
    lists = db.relationship("List")
    registered_on = db.Column(db.DateTime)

    def __init__(self, username, password, email,lists=[]):
        self.username = username
        self.set_password(password)
        self.email = email
        self.lists = lists
        self.registered_on = datetime.utcnow()

    def __repr__(self):
        return '<User %r>' % self.username

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def set_password(self, password):
        self.password = crypt.generate_password_hash(password)

app/forms/user.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, validators


class RegisterForm(Form):
    username = TextField('Username', [validators.Length(min=4, max=80)])
    password = PasswordField('Password', [validators.Required(), validators.EqualTo(
        'confirm_password', message='Passwords are not matching')])

    confirm_password = PasswordField('Retype your password')
    email = TextField('Email Address', [validators.Length(min=6, max=120)])


class LoginForm(Form):
    email = TextField('Email Address', [validators.Length(min=4, max=80)])
    password = PasswordField('Password', [validators.Required()])

app/views/list.py
from flask import Blueprint,  render_template, redirect, url_for, request, flash, abort

from app.models import List, Item
from app.database import db
from app.forms.list import NewListForm
from app.config import csrf

from flask.ext.login import login_required, current_user

list_blueprint = Blueprint(
    'list', __name__, template_folder='../templates/list')

@list_blueprint.route('/<list_id>')
@login_required
def show(list_id):

    a_list = List.query.filter_by(id=list_id).first()

    items = Item.query.filter_by(list_id = list_id).all()
    return render_template('show.html',a_list = a_list, items= items)

@list_blueprint.route('/new',methods=['GET','POST'])
@login_required
def new():
    form = NewListForm(request.form)

    if request.method == 'POST' and form.validate():
        new_list = List(form.title.data)
        current_user.lists.append(new_list)

        db.session.add(new_list)
        db.session.add(current_user)
        db.session.commit()

        flash('New list created successfully')

        return redirect(url_for('user.index'))

    return render_template('new.html', form=form)

@csrf.exempt
@list_blueprint.route('/delete/<list_id>',methods=['POST'])
@login_required
def delete(list_id):

    a_list = List.query.filter_by(id=list_id).first()

    if a_list:
        items=Item.query.filter_by(list_id=list_id).all()

        for item in items:
            db.session.delete(item)

        db.session.delete(a_list)
        db.session.commit()

    return '', 204 # no content

app/views/user.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort

from app.models import User, List
from app.models.user import crypt
from app.forms.user import RegisterForm, LoginForm
from app.database import db

from flask.ext.login import LoginManager, login_user, login_required, logout_user, current_user

import re

user_blueprint = Blueprint(
    'user', __name__, template_folder='../templates/user')

login_manager = LoginManager()
login_manager.login_view = 'user.login'


@user_blueprint.route('/')
@login_required
def index():
    user = current_user
    lists = user.lists
    return render_template('index.html', lists=lists)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)

    if request.method == 'POST' and form.validate():
        user = User(form.username.data, form.password.data, form.email.data)

        # FIXME handle unique constraint in more efficient way !
        if len(User.query.filter_by(username=user.username).all()) > 0:
            flash('Username is already taken')
            return render_template('register.html', form=form)

        if len(User.query.filter_by(email=user.email).all()) > 0:
            flash('Email is already taken')
            return render_template('register.html', form=form)

        db.session.add(user)
        db.session.commit()
        flash('Successfully registered')
        return redirect(url_for('user.login'))

    return render_template('register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # Login and validate the user.
        if(user is not None and crypt.check_password_hash(user.password, form.password.data)):
            login_user(user)
            flash('Logged in successfully')
            next = request.args.get('next')
            if not validate_next(next):
                return abort(400)
            else:
                return redirect(next or url_for('user.index'))
        else:
            flash('Username or password is not correct')
            return redirect(url_for('user.login'))

    return render_template('login.html', form=form)


@user_blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('user.index'))


@login_manager.user_loader
def load_user(user_id):
    """ user loader for flask-login """
    return User.query.get(user_id)


def validate_next(url):
    """ validates next parameter """
    if url is None:
        return True
    re1 = '^\/[a-z0-9/.&=?]*'

    rg = re.compile(re1, re.IGNORECASE | re.DOTALL)
    return rg.search(url) is not None

app/templates/user/index.html
{%extends 'layouts/base.html'%}
{%block body%}
<div class="row">

    {% if not lists %}
      <h1 class='text-center'>Create a new List</h1>

      <h5 class='text-center'>You currently don't have any lists, create some to view your lists</h5>
      <a href="{{url_for('list.new')}}" class="button expand">New List</a>
    {% else %}
    <h1 class='text-center text-bold'>Your Lists</h1>

    <div class="list-index-wrapper small-12 columns">
      {% for a_list in lists %}
        <div class="small-12 large-12 columns list-preview">

          <a href="{{ url_for('list.show',list_id=a_list.id) }}" class='text-center'>
            {{a_list.title}} <span onclick="deleteList(event,$(this),{{a_list.id}})" class="fi-minus right red-link"></span>
          </a>

        </div>
      {%endfor%}
    </div>
    <!-- / .list-index-wrapper -->

    <div class="small-12 large-12 columns">
      <a href="{{url_for('list.new')}}" class="button round small primary bottom right" id="btn-create-list-rounded">Create list</a>
    </div>

    {% endif %}


</div>
<!-- / .row -->

{%endblock%}

app/templates/user/login.html
{%extends 'layouts/base.html' %}
{% block title %}Sign In{% endblock %}
{% from 'helpers/_forms.html' import render_field %}

{% block body %}

  <div class="row">
    <div class="small-12 large-12 columns">

      <h2 class='text-center'>Sign in</h2>
      <form action="" method="post">
        {{form.csrf_token}}

          <div class="row">
            <div class="large-12 columns">
              {%for field in form if field.widget.input_type != 'hidden'%}
                {{render_field(field)}}
              {%endfor%}
            </div>
          </div>

        <input type="submit" value="Login" class="button expand">
      </form>
      <!-- /form -->

      <p>
        not a member ? <a href="{{url_for('user.register')}}">register now</a>
      </p>

    </div>
    <!-- /. small-12 large-12 columns -->
  </div>
  <!-- ./row -->
{% endblock %}

app/templates/user/register.html
{%extends 'layouts/base.html' %}
{% block title %}Sign Up{% endblock %}
{% from 'helpers/_forms.html' import render_field %}


{% block body %}

  <div class="row">
    <div class="small-12 large-12 columns">
      <h2 class='text-center'>Sign Up</h2>
      <form action="" method="post">
        {{form.csrf_token}}

          <div class="row">
            <div class="large-12 columns">
              {%for field in form if field.widget.input_type != 'hidden'%}
                {{render_field(field)}}
              {%endfor%}
            </div>
          </div>

        <input type="submit" value="Register" class="button expand">
      </form>
      <!-- /form -->
    </div>
    <!-- /. small-12 large-12 columns -->
  </div>
  <!-- ./row -->
{% endblock %}